### ISSUE TITLE
use bottleneck signals unchecked on any mod change

### ISSUE THREAD

**Issue by Nexela** [theRustyKnife/CraftingCombinator#34] opened 2017-06-09 02:59 UTC
in crafting_combinator/script/migration.lua line 98

`if not data.mod_changes["Bottleneck"] or not data.mod_changes["Bottleneck"].new_version then`

should probably be

---- Not that... working it out now

`if data.mod_changes and data.mod_changes["Bottleneck"] and not (data.mod_changes["Bottleneck"].new_version) then`

**Comment by theRustyKnife** [comment] 2017-06-09 06:49
I think the original is actually working as intended.

Yes, it will fire every time on_configuration_changed runs and Bottleneck is not installed, but that shouldn't be much of a problem (except the message maybe)... Actually, I think the reason why I did it this way was that the mod wasn't in the event data at all when removed, instead of not having new_version specified as I expected.  

I'm not sure tho, it's been a while since I coded this and it would take more experimentation to check it than I currently have the time for. So if you figure out a way to make it better, feel free to PR, I'll close this as an issue for now tho.

**Closed as completed by theRustyKnife** 2017-06-09 06:49 UTC

**Comment by Nexela** [comment] 2017-06-09 09:59
I tested the bottom version it works here is what is wrong with your version

unistall any mod "YARM" in this case
not data.mod_changes["Bottleneck"]  is nil
not nil is true so the or is ignored
bottleneck gets disabled

`if data.mod_changes and data.mod_changes["Bottleneck"] and not data.mod_changes["Bottleneck"].new_version then`

Correctly works, it only unchecks them when bottleneck is removed like it is supposed too

**Comment by theRustyKnife** [comment] 2017-06-09 10:18
Oh, I see, I was wrong then.  
I'll release this as soon as I have the time (probably in ~5hrs).

Cheers TRK
